### PR TITLE
Fix infinite init

### PR DESCRIPTION
**Pull request by MarcelSoler**
- While trying to run the ros wrapper as a nodeled, with more nodelets attached to it, I've noticed that the rest of nodelets did not start. This was caused because there was a ros::spin in the init(). Hence, that never finished, and the nodeled manager could not start other nodeleds.

To have the same behavior I created a timer that behaves like the spin but without blocking the whole process. I tested it with mynteye P. Both nodeled and node works!

### CODE REVIEW

**Comment by MarcelSoler** [comment]
ping on this! 
@Osenberg-Q @KalmanXiong  @TinySlik  @harjeb  Will this be merged soon?
 any concerns about the pull request?
 Let me know if you need more details or have any questions.

**Review by tahraoui-bor — APPROVED** [review]
I tested this and it solved the problem when running as nodelet. need to have this merged as soon as possible.

**Comment by MarcelSoler** [comment]
Ping on this, any maintainer available?

**Comment by MarcelSoler** [comment]
it's a pity this is not maintained...

**Pull request closed without merging**
